### ISSUE TITLE
Замечания по Product Vision

### ISSUE THREAD

**Issue by nvamelichev** [AndroidM0nkey/hse-java-2022-calc#1]
Product Vision в целом весьма хорош :+1: 

Но есть ряд замечаний:
- [x] Терминология: что означает "рационализировать работу"? Упростить? Сделать более удобной?
- [x] Терминология: почему "...выражениями **особого формата**"/"особыми выражениями"? В чём его особенность? Можно сформулировать более просто, кажется: "Продукт позволяет вычислять сложные выражения в арифметике по модулю N/в модулярной арифметике" или как-то так :-)
- [x] Лучше ещё подчеркнуть, что всё-таки планируются не только арифметические операции, а возможно более обобщённо - "операции [в модулярной арифметике]"
- [x] Не освещён вопрос, будут ли вычисления с произвольной точностью (т.е. с "большими целыми числами")? На практике (при работе с RSA и т.п.) часто в результате вычислений получаются огромные числа. Тут кажется, что это всё-таки важная деталь для конечного пользователя, и её стоит даже в Vision упомянуть (и в User Stories, думаю, тоже)

Жду от вас User Stories, как появятся - заведу для них тоже Issue :-)

**Comment by AndroidM0nkey** [comment]
fixed issues
